spring:
  datasource:
    hikari:
      pool-name: OraclePool
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      auto-commit: true
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
    username: hr
    url: jdbc:oracle:thin:@//localhost:1521/XE
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
