spring:
  application:
    name: jpa

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: OraclePool
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      auto-commit: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 0
