server:
  port: 8585

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pgdb_microservices_dev
    username: ms_user_dev
    password: ms_user_dev
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PostgresPool
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
